2018.02.26 17:33:19 LOG5[ui]: stunnel 5.39 on x86_64-pc-linux-gnu platform
2018.02.26 17:33:19 LOG5[ui]: Compiled/running with OpenSSL 1.0.2g  1 Mar 2016
2018.02.26 17:33:19 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2018.02.26 17:33:19 LOG5[ui]: Reading configuration from file /home/alastair/code/mciframe/chrome-test/stunnel/dev_https
2018.02.26 17:33:19 LOG5[ui]: UTF-8 byte order mark not detected
2018.02.26 17:33:19 LOG5[ui]: FIPS mode disabled
2018.02.26 17:33:19 LOG4[ui]: Insecure file permissions on stunnel.pem
2018.02.26 17:33:19 LOG5[ui]: Configuration successful
2018.02.26 17:33:43 LOG5[0]: Service [https] accepted connection from 127.0.0.1:49850
2018.02.26 17:33:43 LOG3[0]: SSL_accept: 1408F10B: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
2018.02.26 17:33:43 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2018.02.26 17:33:43 LOG5[1]: Service [https] accepted connection from 127.0.0.1:49852
2018.02.26 17:33:43 LOG3[1]: SSL_accept: 1408F10B: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
2018.02.26 17:33:43 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2018.02.26 17:33:48 LOG5[2]: Service [https] accepted connection from 127.0.0.1:49896
2018.02.26 17:33:48 LOG3[2]: SSL_accept: 1408F10B: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
2018.02.26 17:33:48 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2018.02.26 17:34:06 LOG5[3]: Service [https] accepted connection from 127.0.0.1:50044
2018.02.26 17:34:06 LOG5[3]: s_connect: connected 127.0.0.1:5000
2018.02.26 17:34:06 LOG5[3]: Service [https] connected remote server from 127.0.0.1:45708
2018.02.26 17:34:06 LOG5[3]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2018.02.26 17:34:08 LOG5[4]: Service [https] accepted connection from 127.0.0.1:50064
2018.02.26 17:34:08 LOG3[4]: s_connect: connect ::1:5000: Connection refused (111)
2018.02.26 17:34:08 LOG5[4]: s_connect: connected 127.0.0.1:5000
2018.02.26 17:34:08 LOG5[4]: Service [https] connected remote server from 127.0.0.1:45730
2018.02.26 17:34:08 LOG5[4]: Connection closed: 179 byte(s) sent to TLS, 427 byte(s) sent to socket
2018.02.26 17:34:08 LOG5[5]: Service [https] accepted connection from 127.0.0.1:50070
2018.02.26 17:34:08 LOG5[5]: s_connect: connected 127.0.0.1:5000
2018.02.26 17:34:08 LOG5[6]: Service [https] accepted connection from 127.0.0.1:50074
2018.02.26 17:34:08 LOG5[5]: Service [https] connected remote server from 127.0.0.1:45734
2018.02.26 17:34:08 LOG5[5]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2018.02.26 17:34:08 LOG5[6]: s_connect: connected 127.0.0.1:5000
2018.02.26 17:34:08 LOG5[6]: Service [https] connected remote server from 127.0.0.1:45738
2018.02.26 17:34:08 LOG5[6]: Connection closed: 380 byte(s) sent to TLS, 399 byte(s) sent to socket
2018.02.26 17:34:11 LOG5[7]: Service [https] accepted connection from 127.0.0.1:50106
2018.02.26 17:34:11 LOG3[7]: SSL_accept: 1408F10B: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
2018.02.26 17:34:11 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2018.02.26 17:34:19 LOG5[cron]: Updating DH parameters
2018.02.26 17:34:21 LOG5[8]: Service [https] accepted connection from 127.0.0.1:50192
2018.02.26 17:34:21 LOG5[8]: s_connect: connected 127.0.0.1:5000
2018.02.26 17:34:21 LOG5[8]: Service [https] connected remote server from 127.0.0.1:45856
2018.02.26 17:34:21 LOG5[8]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2018.02.26 17:34:21 LOG5[9]: Service [https] accepted connection from 127.0.0.1:50196
2018.02.26 17:34:21 LOG5[9]: s_connect: connected 127.0.0.1:5000
2018.02.26 17:34:21 LOG5[9]: Service [https] connected remote server from 127.0.0.1:45860
2018.02.26 17:34:21 LOG5[9]: Connection closed: 1224 byte(s) sent to TLS, 611 byte(s) sent to socket
2018.02.26 17:34:58 LOG5[10]: Service [https] accepted connection from 127.0.0.1:50500
2018.02.26 17:34:58 LOG5[10]: s_connect: connected 127.0.0.1:5000
2018.02.26 17:34:58 LOG5[10]: Service [https] connected remote server from 127.0.0.1:46164
2018.02.26 17:34:58 LOG5[11]: Service [https] accepted connection from 127.0.0.1:50504
2018.02.26 17:34:58 LOG5[10]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2018.02.26 17:34:58 LOG5[11]: s_connect: connected 127.0.0.1:5000
2018.02.26 17:34:58 LOG5[11]: Service [https] connected remote server from 127.0.0.1:46168
2018.02.26 17:34:58 LOG3[11]: TLS fd: Connection reset by peer (104)
2018.02.26 17:34:58 LOG5[11]: Connection closed: 1224 byte(s) sent to TLS, 611 byte(s) sent to socket
2018.02.26 17:37:18 LOG5[cron]: DH parameters updated
